### ISSUE TITLE
Support SDF to URDF conversion

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/sdformat#135]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/135)) by Nate Koenig (Bitbucket: [Nathan Koenig](https://bitbucket.org/%7Bc862cdd9-fcc8-4419-9fc7-e20db14b8fcb%7D/)).**

----------------------------------------

**Comment by chapulina** [comment]
* #273 

is a duplicate of this one, but that one has more comments, so I'll close this in favor of that.
