### ISSUE TITLE
Embed SDF XML files into library

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/sdformat#141]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/141)) by clalancette (Bitbucket: [clalancette](https://bitbucket.org/%7B02b311e1-297d-4232-89c4-5485d0a02911%7D/), GitHub: [clalancette](https://github.com/clalancette)).**

----------------------------------------
I'm considering changing the sdformat library so that it directly embeds the SDF XML files (basically all of the contents of the sdf/ subdirectory) into resource strings in the library.  They would be separate XML files in the source repository, but at build time we would run an external program to make resource strings out of them, and then build that into the library.

The main benefit to doing so would be to remove any code within the library that goes looking through the filesystem to find these files.  This would make it faster, and remove a dependency on boost::filesystem.  It would also make it easier for the tests, and potentially easier to deploy the library in general, since you will now only need the .so .  It may also be slightly faster, though this is probably a minor benefit.

The potential downsides to doing so are removing visibility of the XML files from the end-user, but I'm not sure that is hugely useful anyway.  It also requires a rebuild of the library to "upgrade" the SDF XML files, but that seems pretty minor.

Are there any other objections to this plan?

**Comment by azeey** [comment]
Resolved by https://github.com/ignitionrobotics/sdformat/issues/141 and https://github.com/ignitionrobotics/sdformat/pull/270
