### ISSUE TITLE
Model::Load should not emit duplicate child element warning for <plugin> elements

### ISSUE THREAD

**Issue by azeey** [ignitionrobotics/sdformat#294]
`<plugin>` elements should be ignored when validating a model for name uniqueness, but `Model::Load` emits a warning if it encounters multiple `<plugin>` elements with the same name attribute.

Related: ignitionrobotics/ign-gazebo#164

**Comment by scpeters** [comment]
In my opinion, `ign-gazebo` is misusing the `//plugin/@name` attribute by storing a non-unique class name there. I think it would be cleaner to use a custom attribute for the class name.

In general I think the parser shouldn't bother about things like `//plugin/@name`, but this attribute is in the spec saying that it [must be unique](https://github.com/osrf/sdformat/blob/master/sdf/1.7/plugin.sdf#L4-L5). So if we're going to change the parser to eliminate this warning, then I think we would also need to change the spec.

Another option is for ign-gazebo to start using a custom element for plugins, like `<ign-gazebo:system>` or something.

**Comment by azeey** [comment]
Fixed by #721
