### ISSUE TITLE
Make SDFormat lighter weight, by removing boost.

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/sdformat#34]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/34)) by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------
Strip boost dependency.  This will make it more portable.

Example of what we need from boost can be found in [this directory](https://github.com/erwincoumans/experiments/tree/master/dynamics/ros/boost_replacement)

**Comment by azeey** [comment]
Resolved by https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/438/page/1
