### ISSUE TITLE
Should have a parser option or command line flag to preserve includes when converting to string

### ISSUE THREAD

**Issue by azeey** [ignitionrobotics/sdformat#522]
## Desired behavior
It would be nice for information contained in the `<include>` element be preserved when converting `sdf::Element` objects to string. This information is being stored in `sdf::Element` as of #509. Currently, the included models (or other entities) are expanded into the parent model with the parameters in the `<include>` element being used to override values in the included model. Thus, when the corresponding `sdf::Element` of the parent model is converted to a string, we get the string of the expanded child model.

## Alternatives considered
The alternative is to always preserve the `<include>` element, but this would be a breaking change.

## Implementation suggestion
Add an option in `sdf::ParserConfig` and and a command line flag to `ign sdf -p`

**Comment by jennuine** [comment]
Per VC, will leave `ign sdf -p` the way it is currently (expands `<include>` tags) and will add new command flag to preserve `<include>`
