### ISSUE TITLE
Should emit an error if `//pose/@relative_to` is specified on the top level model of a model file

### ISSUE THREAD

**Issue by azeey** [ignitionrobotics/sdformat#567]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build? either, v11.1.0

## Description
* Expected behavior: The top level model of a model file does not have sibling frames. Thus, its pose cannot have a non-empty `relative_to` attribute. Given the following model file
```xml
<sdf version="1.8">
  <model name="M">
    <pose relative_to="some_frame"/>
    <link name="L"/>
   </model>
</sdf>
```
libsdformat should at least emit an error saying `some_frame` is not found. It would also be nice to inform the user that a non-empty `relative_to` is invalid in this context.

* Actual behavior: No error is emitted

## Steps to reproduce
1. Put the above snippet in an SDFormat file
2. Run `ign sdf -k <file name>`

## Output
It prints `Valid.` instead of errors.

**Comment by EricCousineau-TRI** [comment]
Came up in: https://github.com/RobotLocomotion/drake/pull/14401#pullrequestreview-658491103
