### ISSUE TITLE
Segfault when parsing incorrect SDF.

### ISSUE THREAD

**Issue by Mokosha** [ignitionrobotics/sdformat#590]
`elemXml`  may be undefined on this line since the loop prior to it terminates on it being `nullptr`:

https://github.com/osrf/sdformat/blob/85ebd9ba6774d1cdc89f9f03ab98da4d43267442/src/parser.cc#L1502

**Comment by azeey** [comment]
Yeah, I think we should be using `_sdf->LineNumber()` instead.
