### ISSUE TITLE
Missing SDF files in sdf/1.8/CMakeLists.txt

### ISSUE THREAD

**Issue by FirefoxMetzger** [ignitionrobotics/sdformat#629]
I've been toying with this repo because I want to create type-annotated python bindings for the SDFormat. Both for validation and for a better time while programming (IDE auto-completion). To make a long story short, I am generating python stub files from the schemas generated during this repo's build and the stub generator (external: xsdata) warns that a few class schemas could not be found for v1.8 (haven't tested others yet).

For some warnings the cause seems to trace back to [`CMakeLists.txt`](https://github.com/ignitionrobotics/sdformat/blob/sdf11/sdf/1.8/CMakeLists.txt) which is missing 3 SDFs:

- lidar.sdf
- air_pressure.sdf
- particle_emitter.sdf

which leads to missing `*.xsd` files. Adding the respective lines solves this issue as expected and generates the missing `*.xsd` files.

Is this intentional or a bug? If the latter, I can submit a PR.

**Comment by chapulina** [comment]
Nice catch, it's unintentional, these are the latest files added and were simply forgotten.

> I want to create type-annotated python bindings for the SDFormat.

Nice! Let us (and the [community](https://community.gazebosim.org/)) know when you're done, we'd love to try it out!
