### ISSUE TITLE
Invalid default value for elements of type <time>

### ISSUE THREAD

**Issue by FirefoxMetzger** [ignitionrobotics/sdformat#642]
In `types.xsd` time is defined as a simple double, however inside `state.sdf` a string value of the form `"0 0"` is used as default. The documentation agrees with the latter and says it should be of the form `"{seconds} {nanoseconds}`.

I implemented a local fix inside `types.xsd` of the form

```xml
  <xsd:simpleType name="time">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="\d+ \d+"/>
    </xsd:restriction>
  </xsd:simpleType>
```

However, it still makes sense to bring it up as an issue here, since I don't know if this is the preferred solution.

**Comment by chapulina** [comment]
The suggested fix makes sense to me

**Comment by azeey** [comment]
I believe "{seconds} {nanoseconds}" is what's used by Gazebo classic, so the fix makes sense to me too.
