### ISSUE TITLE
SDFormat10 package not available on Ubuntu

### ISSUE THREAD

**Issue by varunagrawal** [ignitionrobotics/sdformat#655]
## Environment
* OS Version: 20.04
* Binary build for SDFormat10.

## Description
* Expected behavior: As per the README, running `apt-get install libsdformat10` should install the SDFormat package from Ubuntu's repositories.
* Actual behavior: `apt-get` cannot find the package.

## Steps to reproduce

1. Take a fresh version of Ubuntu 20.04 (I used a docker image to verify this).
2. Follow the README and run `sudo apt-get -y install libsdformat10`.
3. See the failure.

## Output

```sh
root@447c4bd99237:/# apt -y install sdformat10
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package sdformat10
```

**Comment by varunagrawal** [comment]
My guess is that we need to run these extra commands before trying to install:

```
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
sudo apt-get update

sudo apt-get -y install libsdformat10  # This should work now
```

If so, this should be added to the README.

**Comment by azeey** [comment]
Yes, we currently only have `libsdformat6` on Ubuntu 20.04, so if other versions are needed, it's necessary to add the `packages.osrfoundation.org` repo. Do you mind creating a PR with your suggestion?
