### ISSUE TITLE
SDF v1.7 is missing //light/intensity but `/test/sdf/world_complete.sdf` uses it

### ISSUE THREAD

**Issue by FirefoxMetzger** [ignitionrobotics/sdformat#670]
Here is the relevant snippet of the SDF test file:

https://github.com/ignitionrobotics/sdformat/blob/5a8e796c1c8c8c8c51fd628786e726631f83e8a4/test/sdf/world_complete.sdf#L53-L62

However, the spec mentions //light/intensity starting with SDFv1.8 not SDFv1.7. Is this an omission of the spec, or an invalid test file? 

If the former, I can submit a PR that adds it once someone lets me know which version it was introduced in.

In the latter case, should the version of the file be bumped to v1.8? In this case, //particle_emitter/particle_scatter_ratio has been removed in v1.8 and needs fixing in the test file. Alternatively, the //light/intensity element could be removed (fixes the problem).

**Comment by azeey** [comment]
`//light/intensity` was introduced in #484. I think it makes sense to update the version in the file to 1.8. 

`//particle_emitter/particle_scatter_ratio` was added to the `sdf10` branch in https://github.com/ignitionrobotics/sdformat/pull/547. I think it was just left out when forward porting to the `sdf11` branch-- a problem we don't a good solution for (https://github.com/ignitionrobotics/sdformat/issues/571).
