### ISSUE TITLE
preserveFixedJoint flag in sdf::readFile

### ISSUE THREAD

**Issue by varunagrawal** [ignitionrobotics/sdformat#814]
## Desired behavior
Would having a `preserveFixedJoint` flag in the `sdf::readFile` function be a good idea? Our projects would like to preserve fixed joints but we would like to avoid having to manually edit each and every SDF/URDF file that our users use.

Since we parse the SDF/URDF file directly using the `readFile` function, it makes sense to have a flag there with a sensible, backwards-compatible default.

## Alternatives considered
The alternative would be to manually update each SDF/URDF file to add the necessary `<gazebo>` tags. This is cumbersome and error-prone in case someone forgets to do it.

## Implementation suggestion
I can open a PR for this and we can discuss the overall design there. I don't believe it will be a big change, just exposing some functionality programmatically.

**Comment by scpeters** [comment]
I think you may want to add it to [ParserConfig.hh](https://github.com/ignitionrobotics/sdformat/blob/sdf12/include/sdf/ParserConfig.hh)

**Comment by varunagrawal** [comment]
Great! Will there be a plan to backport this to SDFormat10 and SDFormat11?

**Comment by scpeters** [comment]
> Great! Will there be a plan to backport this to SDFormat10 and SDFormat11?

it is already in libsdformat11, and libsdformat10 has reached end-of-life

* https://github.com/ignitionrobotics/sdformat/blob/sdf11/include/sdf/ParserConfig.hh

**Comment by azeey** [comment]
Closed by #815
