### ISSUE TITLE
ign sdf --inertial-stats: compute and print aggregate inertial statistics of a model

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/sdformat#832]
## Desired behavior

It would be very convenient if the `ign sdf` tool could compute aggregate inertial properties of a model:

* total mass
* aggregate center of mass
* aggregate moment of inertia with respect to lumped center of mass

## Implementation suggestion

The [ignition:math::Inertial](https://github.com/ignitionrobotics/ign-math/blob/ignition-math6_6.10.0/include/ignition/math/Inertial.hh#L202-L268) class can be constructed for each link and then aggregated with the addition operator to compute these statistics. See the [Inertial_TEST.cc](https://github.com/ignitionrobotics/ign-math/blob/ign-math6/src/Inertial_TEST.cc#L368-L543) unit test for an example using the addition operator.

**Comment by adityapande-1995** [comment]
Prototype script here : https://github.com/adityapande-1995/inertial_tools
