### ISSUE TITLE
SDF -> USD conversion support

### ISSUE THREAD

**Issue by adlarkin** [ignitionrobotics/sdformat#845]
This issue is meant to track the progress of converting SDF to [USD](https://graphics.pixar.com/usd/release/index.html), which is currently a work in progress.

@ahcorde if there's anything I'm missing in the feature list below (or if anything seems incorrect/out of date), feel free to modify the feature list directly.

## Supported
* World's gravity information
* Lights
    - `//light/direction` is currently ignored (USD lights will point down by default)
    - `//light/diffuse` and `//light/specular` are currently ignored, but a potential workaround for these elements is to apply a material to the USD light

## In Progress
* Links (https://github.com/ignitionrobotics/sdformat/pull/828)
    - static/non-static
    - mass, inertia, center of mass
    - basic ground plane support (USD doesn’t have a plane geometry yet, so the workaround is to make a wide, thin box that represents a place)
    - lights attached to links
    - visual
        - Box, cylinder, sphere, mesh, capsule, plane, ellipsoid geometries
            - Mesh geometry support is limited to points, lines, and triangles submesh primitive types
    - collisions
        - Limited support. Currently, a collision is created for every visual, with the collision geometry matching the link’s visual geometry. SDF supports setting collisions that can differ from link geometries (perhaps users want a simpler collision shape, for example)
* Sensors (https://github.com/ignitionrobotics/sdformat/pull/830)
    - Camera, lidar, imu are supported
        - `//lidar/scan/horizontal/samples` and `//lidar/scan/vertical/samples` currently aren’t being parsed to the USD lidar sensor
* Materials (#831)
    - Ignition fuel resources are searched for (`$HOME/.ignition/fuel`)
* Joints (#837)
    - Support for revolute, ball, fixed, and prismatic joint types
* USD-specific error codes (#836)

## Not Supported
* SDF files with multiple worlds (the `sdf2usd` parser executable only supports SDF files with exactly one world)
* Nested models
* Plugins

### Additional context
Here are past PRs related to this work that have been merged:
* #817
* #818

**Comment by ahcorde** [comment]
As I commented in this PR https://github.com/ignitionrobotics/sdformat/pull/762 This task is done!
